import Head from "next/head"
import Link from "next/link"

export default function FirstPost() {
  return (
    <>
      <Head>
        <title>First</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Enter</h1>
      <h2>aaa</h2>
      <Link href="/">TOP</Link>
    </>
  )
}
